version: '3.8'

services:
  mesero-app:
    image: ghcr.io/saturnx-dev/mesero:main
    container_name: mesero_santas_alitas
    ports:
      - "5806:3000"
    volumes:
      - /volume1/docker/alitas:/app/data
    restart: always
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/data/restaurant.db
